In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\raw\raw_car_listings.csv")
df.head()

                     Title       Price Kilometers Fuel_Type Transmission
0         2015 Hyundai Eon  ₹1.72 lakh  43,518 km    Petrol       Manual
1  2017 Maruti Wagon R 1.0  ₹2.39 lakh  42,678 km    Petrol       Manual
2      2018 Datsun Redi Go  ₹1.64 lakh  60,214 km       CNG       Manual
3          2020 Tata NEXON  ₹5.20 lakh  50,912 km    Petrol       Manual
4        2020 Renault Kwid  ₹2.50 lakh  68,431 km    Petrol       Manual

In [2]:
import re

def extract_final_price(price_str):

    if pd.isna(price_str):
        return None

    numbers = re.findall(r"\d+\.\d+|\d+", str(price_str))

    if numbers:
        final_price_lakh = float(numbers[-1])

        return int(final_price_lakh*100000)

    return None

df['Clean_Price'] = df['Price'].apply(extract_final_price)

df[['Price', 'Clean_Price']].head()

        Price  Clean_Price
0  ₹1.72 lakh       172000
1  ₹2.39 lakh       239000
2  ₹1.64 lakh       164000
3  ₹5.20 lakh       520000
4  ₹2.50 lakh       250000

In [3]:
print(f"Total rows processed: {df.shape[0]}")

df[['Price','Clean_Price']].sample(10)

Total rows processed: 4258

            Price  Clean_Price
2894   ₹8.50 lakh       850000
2028   ₹0.83 lakh        83000
1034   ₹2.67 lakh       267000
1643   ₹4.80 lakh       480000
4121   ₹5.90 lakh       590000
2466   ₹4.70 lakh       470000
3867   ₹5.46 lakh       546000
97     ₹2.99 lakh       299000
2953  ₹13.50 lakh      1350000
3962   ₹9.77 lakh       977000

In [4]:
def clean_kilometer(km_str):

    if pd.isna(km_str):
        return None

    clean_str = str(km_str).replace(',','').replace(' km','').replace('km','').strip()

    numbers = re.findall(r'\d+', clean_str)

    if numbers:
        return int(''.join(numbers))

    return None 

df['Clean_Kilometers'] = df['Kilometers'].apply(clean_kilometer)

df[['Kilometers', 'Clean_Kilometers']].sample(5)

     Kilometers  Clean_Kilometers
3047  24,018 km             24018
4066  38,785 km             38785
471   21,452 km             21452
600   60,859 km             60859
2155  28,028 km             28028

In [5]:
from datetime import datetime
df['Title'] = df['Title'].fillna('')

title_splits = df['Title'].str.split(' ', n = 2, expand = True)

df['Year'] = title_splits[0]
df['Brand'] = title_splits[1]
df['Model'] = title_splits[2]

df['Year'] = pd.to_numeric(df['Year'],errors='coerce')

current_year = datetime.now().year
df['Car_Age'] = current_year - df['Year']
df['Km_per_Year'] = df['Clean_Kilometers'] / (df['Car_Age'] + 1)

df_clean = df.drop(columns=['Title', 'Price', 'Kilometers', 'Year'])
df_clean.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Brand,Model,Car_Age,Km_per_Year
0,Petrol,Manual,172000,43518,Hyundai,Eon,11,3626.500000
1,Petrol,Manual,239000,42678,Maruti,Wagon R 1.0,9,4267.800000
2,CNG,Manual,164000,60214,Datsun,Redi Go,8,6690.444444
3,Petrol,Manual,520000,50912,Tata,NEXON,6,7273.142857
4,Petrol,Manual,250000,68431,Renault,Kwid,6,9775.857143

In [6]:
df_clean.to_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\processed\clean_car_listing.csv", index = False)
print("Clean data Successfully saved to data/processed")

Clean data Successfully saved to data/processed