In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\raw\raw_car_listings.csv")
df.head()

                     Title       Price Kilometers Fuel_Type Transmission
0      2023 Nissan MAGNITE  ₹3.82 lakh  40,563 km    Petrol       Manual
1         2015 Hyundai Eon  ₹1.72 lakh  43,518 km    Petrol       Manual
2  2017 Maruti Wagon R 1.0  ₹2.39 lakh  42,678 km    Petrol       Manual
3       2017 Maruti Baleno  ₹3.05 lakh  50,894 km    Petrol       Manual
4        2017 Maruti Swift  ₹2.23 lakh  79,321 km    Petrol       Manual

In [8]:
import re

def extract_final_price(price_str):

    if pd.isna(price_str):
        return None

    numbers = re.findall(r"\d+\.\d+|\d+", str(price_str))

    if numbers:
        final_price_lakh = float(numbers[-1])

        return int(final_price_lakh*100000)

    return None

df['Clean_Price'] = df['Price'].apply(extract_final_price)

df[['Price', 'Clean_Price']].head()

        Price  Clean_Price
0  ₹3.82 lakh       382000
1  ₹1.72 lakh       172000
2  ₹2.39 lakh       239000
3  ₹3.05 lakh       305000
4  ₹2.23 lakh       223000

In [9]:
print(f"Total rows processed: {df.shape[0]}")

df[['Price','Clean_Price']].sample(10)

Total rows processed: 500

          Price  Clean_Price
218  ₹2.98 lakh       298000
345  ₹4.17 lakh       417000
229  ₹3.25 lakh       325000
238  ₹3.24 lakh       324000
343  ₹6.12 lakh       612000
444  ₹1.27 lakh       127000
42   ₹3.23 lakh       323000
380  ₹4.40 lakh       440000
428  ₹6.10 lakh       610000
458  ₹1.32 lakh       132000

In [10]:
def clean_kilometer(km_str):

    if pd.isna(km_str):
        return None

    clean_str = str(km_str).replace(',','').replace(' km','').replace('km','').strip()

    numbers = re.findall(r'\d+', clean_str)

    if numbers:
        return int(''.join(numbers))

    return None 

df['Clean_Kilometers'] = df['Kilometers'].apply(clean_kilometer)

df[['Kilometers', 'Clean_Kilometers']].sample(5)

    Kilometers  Clean_Kilometers
145  74,329 km             74329
56   75,061 km             75061
28   65,394 km             65394
112  65,480 km             65480
253  35,077 km             35077

In [11]:
df['Title'] = df['Title'].fillna('')

title_splits = df['Title'].str.split(' ', n = 2, expand = True)

df['Year'] = title_splits[0]
df['Brand'] = title_splits[1]
df['Model'] = title_splits[2]

df['Year'] = pd.to_numeric(df['Year'],errors='coerce')

df_clean = df.drop(columns=['Title', 'Price', 'Kilometers'])
df_clean.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Year,Brand,Model
0,Petrol,Manual,382000,40563,2023,Nissan,MAGNITE
1,Petrol,Manual,172000,43518,2015,Hyundai,Eon
2,Petrol,Manual,239000,42678,2017,Maruti,Wagon R 1.0
3,Petrol,Manual,305000,50894,2017,Maruti,Baleno
4,Petrol,Manual,223000,79321,2017,Maruti,Swift

In [12]:
df_clean.to_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\processed\clean_car_listing.csv", index = False)
print("Clean data Successfully saved to data/processed")

Clean data Successfully saved to data/processed