In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\raw\raw_car_listing.csv")
df.head()

                 Title             Price Kilometers Fuel_Type Transmission
0     2015 Hyundai Eon  ₹1.88L₹1.72 lakh  43,518 km    Petrol       Manual
1    2017 Maruti Swift  ₹2.70L₹2.23 lakh  79,321 km    Petrol       Manual
2      2021 Tata Tiago  ₹3.75L₹3.04 lakh  70,488 km    Petrol       Manual
3  2018 Datsun Redi Go  ₹1.85L₹1.64 lakh  60,214 km       CNG       Manual
4  2020 Renault TRIBER  ₹3.56L₹2.91 lakh  39,097 km    Petrol       Manual

In [8]:
import re

def extract_final_price(price_str):

    if pd.isna(price_str):
        return None

    numbers = re.findall(r"\d+\.\d+|\d+", str(price_str))

    if numbers:
        final_price_lakh = float(numbers[-1])

        return int(final_price_lakh*100000)

    return None

df['Clean_Price'] = df['Price'].apply(extract_final_price)

df[['Price', 'Clean_Price']].head()

              Price  Clean_Price
0  ₹1.88L₹1.72 lakh       172000
1  ₹2.70L₹2.23 lakh       223000
2  ₹3.75L₹3.04 lakh       304000
3  ₹1.85L₹1.64 lakh       164000
4  ₹3.56L₹2.91 lakh       291000

In [9]:
print(f"Total rows processed: {df.shape[0]}")

df[['Price','Clean_Price']].sample(10)

Total rows processed: 40

               Price  Clean_Price
11  ₹3.90L₹3.44 lakh       344000
24  ₹2.32L₹1.95 lakh       195000
26  ₹2.04L₹1.44 lakh       144000
30  ₹4.28L₹3.48 lakh       348000
38  ₹4.59L₹3.85 lakh       385000
1   ₹2.70L₹2.23 lakh       223000
14  ₹7.76L₹7.35 lakh       735000
27  ₹4.08L₹3.58 lakh       358000
32  ₹5.76L₹5.42 lakh       542000
6   ₹2.05L₹1.61 lakh       161000

In [10]:
def clean_kilometer(km_str):

    if pd.isna(km_str):
        return None

    clean_str = str(km_str).replace(',','').replace(' km','').replace('km','').strip()

    numbers = re.findall(r'\d+', clean_str)

    if numbers:
        return int(''.join(numbers))

    return None 

df['Clean_Kilometers'] = df['Kilometers'].apply(clean_kilometer)

df[['Kilometers', 'Clean_Kilometers']].sample(5)

   Kilometers  Clean_Kilometers
23  26,519 km             26519
10  66,646 km             66646
1   79,321 km             79321
31  62,667 km             62667
37  71,347 km             71347

In [12]:
df['Title'] = df['Title'].fillna('')

title_splits = df['Title'].str.split(' ', n = 2, expand = True)

df['Year'] = title_splits[0]
df['Brand'] = title_splits[1]
df['Model'] = title_splits[2]

df['Year'] = pd.to_numeric(df['Year'],errors='coerce')

df_clean = df.drop(columns=['Title', 'Price', 'Kilometers'])
df_clean.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Year,Brand,Model
0,Petrol,Manual,172000,43518,2015,Hyundai,Eon
1,Petrol,Manual,223000,79321,2017,Maruti,Swift
2,Petrol,Manual,304000,70488,2021,Tata,Tiago
3,CNG,Manual,164000,60214,2018,Datsun,Redi Go
4,Petrol,Manual,291000,39097,2020,Renault,TRIBER

In [13]:
df_clean.to_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\processed\clean_car_listing.csv", index = False)
print("Clean data Successfully saved to data/processed")

Clean data Successfully saved to data/processed